-- Add business fields to products with DB-friendly snake_case names

alter table public.products
  add column if not exists item_status text,
  add column if not exists reg_date text,
  add column if not exists reg_user text,
  add column if not exists last_update_date text,
  add column if not exists last_update_user text,
  add column if not exists domestic_overseas text,
  add column if not exists item_subcategory text,
  add column if not exists importance text,
  add column if not exists managing_department text,
  add column if not exists manager text,
  add column if not exists item_category text,
  add column if not exists item_midcategory text,
  add column if not exists shipping_type text,
  add column if not exists is_main_item text,
  add column if not exists is_set_item text,
  add column if not exists is_bom_registered text,
  add column if not exists has_process_materials text,
  add column if not exists lot_control text,
  add column if not exists serial_control text,
  add column if not exists asset_category text,
  add column if not exists inspection_target text,
  add column if not exists shelf_life_type text,
  add column if not exists shelf_life_period text,
  add column if not exists sm_asset_grp text,
  add column if not exists default_supplier text,
  add column if not exists vat_type text,
  add column if not exists sale_price_includes_vat text,
  add column if not exists attachment text,
  add column if not exists image_url text,
  add column if not exists main_name text,
  add column if not exists main_code text,
  add column if not exists main_spec text,
  add column if not exists spec text,
  add column if not exists unit text,
  add column if not exists item_subdivision text,
  add column if not exists keywords_alias text,
  add column if not exists specification text,
  add column if not exists special_notes text,
  add column if not exists cas_no text,
  add column if not exists moq text,
  add column if not exists package_unit text,
  add column if not exists manufacturer text,
  add column if not exists country_of_manufacture text,
  add column if not exists source_of_origin_method text,
  add column if not exists plant_part text,
  add column if not exists country_of_origin text,
  add column if not exists nmpa_no text,
  add column if not exists allergen text,
  add column if not exists furocoumarins text,
  add column if not exists efficacy text,
  add column if not exists patent text,
  add column if not exists paper text,
  add column if not exists clinical text,
  add column if not exists expiration_date text,
  add column if not exists storage_location text,
  add column if not exists storage_method1 text,
  add column if not exists stability_note1 text,
  add column if not exists storage_note1 text,
  add column if not exists safety_handling1 text,
  add column if not exists notice_coa3_en_1 text,
  add column if not exists notice_coa3_kr_1 text,
  add column if not exists notice_comp_kr_1 text,
  add column if not exists notice_comp_en_1 text,
  add column if not exists caution_origin_1 text,
  add column if not exists cert_organic text,
  add column if not exists cert_kosher text,
  add column if not exists cert_halal text,
  add column if not exists cert_vegan text,
  add column if not exists cert_isaaa text,
  add column if not exists cert_rspo text,
  add column if not exists cert_reach text,
  add column if not exists expiration_date2 text,
  add column if not exists storage_method2 text,
  add column if not exists stability_note2 text,
  add column if not exists storage_note2 text,
  add column if not exists safety_handling2 text,
  add column if not exists notice_coa3_en_2 text,
  add column if not exists notice_coa3_kr_2 text,
  add column if not exists notice_comp_kr_2 text,
  add column if not exists notice_comp_en_2 text,
  add column if not exists caution_origin_2 text;











